version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: infraapi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ticketdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql?allowPublicKeyRetrieval=true -schemas=ticketdb -user=user -password=password -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      mysql:
        condition: service_healthy

  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    ports:
      - 3001:8080
    volumes:
      - ./docker/wiremock:/home/wiremock
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]

volumes:
  mysql_data:
